apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmap.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - web-deployment.yaml
  - services.yaml
  - migrate-job.yaml
  - policies.yaml
  - networkpolicies.yaml
