apiVersion: v1
kind: ServiceAccount
metadata:
  name: korpus-api
  namespace: korpus
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: korpus-worker
  namespace: korpus
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: korpus-web
  namespace: korpus
automountServiceAccountToken: false
