"""Read-only structural contracts shared by adaptive validators and values."""

from __future__ import annotations

from typing import Protocol


class RuntimeKnobsLike(Protocol):
    @property
    def candidate_budget(self) -> int: ...
    @property
    def retrieval_timeout_ms(self) -> int: ...
    @property
    def minimum_score(self) -> float: ...
    @property
    def minimum_query_coverage(self) -> float: ...
    @property
    def minimum_support_score(self) -> float: ...


class AdaptationPolicyLike(Protocol):
    @property
    def min_candidate_budget(self) -> int: ...
    @property
    def max_candidate_budget(self) -> int: ...
    @property
    def candidate_step(self) -> int: ...
    @property
    def min_timeout_ms(self) -> int: ...
    @property
    def max_timeout_ms(self) -> int: ...
    @property
    def timeout_step_ms(self) -> int: ...
    @property
    def safety_step(self) -> float: ...
    @property
    def max_safety_threshold(self) -> float: ...
    @property
    def min_samples(self) -> int: ...
    @property
    def high_error_rate(self) -> float: ...
    @property
    def high_contradiction_rate(self) -> float: ...
    @property
    def high_overload_rate(self) -> float: ...
    @property
    def high_latency_ms(self) -> float: ...
    @property
    def low_recall(self) -> float: ...
    @property
    def healthy_error_rate(self) -> float: ...
    @property
    def healthy_overload_rate(self) -> float: ...
    @property
    def healthy_latency_ms(self) -> float: ...
    @property
    def healthy_windows_for_recall_expansion(self) -> int: ...
    @property
    def cooldown_windows(self) -> int: ...


class ObservationWindowLike(Protocol):
    @property
    def sequence(self) -> int: ...
    @property
    def samples(self) -> int: ...
    @property
    def p95_latency_ms(self) -> float: ...
    @property
    def error_rate(self) -> float: ...
    @property
    def contradiction_rate(self) -> float: ...
    @property
    def overload_rate(self) -> float: ...
    @property
    def recall_at_20(self) -> float: ...


class AdaptationStateLike(Protocol):
    @property
    def last_change_sequence(self) -> int: ...
    @property
    def consecutive_healthy_windows(self) -> int: ...


class JudgedCandidateLike(Protocol):
    @property
    def relevance(self) -> int: ...
    @property
    def authority_score(self) -> float: ...
    @property
    def semantic_score(self) -> float: ...
    @property
    def temporal_score(self) -> float: ...
