import {readFile} from "node:fs/promises";
import {fileURLToPath} from "node:url";
const asset = (file) => fileURLToPath(new URL(`../${file}`, import.meta.url));
const read = (file) => readFile(asset(file), "utf8");
function cssFontFamily(value) { return value.map((part) => /\s/.test(part) && !part.startsWith("ui-") ? `"${part.replaceAll('"','\\"')}"` : part).join(", "); }
function cssValue(token) { const override=token?.$extensions?.["org.korpus.css"]?.css; if(override)return override; switch(token.$type){case"color":return token.$value.hex;case"dimension":return `${token.$value.value}${token.$value.unit}`;case"fontFamily":return cssFontFamily(token.$value);case"number":return String(token.$value);case"string":return token.$value;default:throw new Error(`unsupported CSS token type: ${token.$type}`);} }
function collectCssTokens(node, output=[]) { if(!node||typeof node!=="object"||Array.isArray(node))return output; if(Object.hasOwn(node,"$value")){const variable=node?.$extensions?.["org.korpus.css"]?.variable;if(variable)output.push([variable,cssValue(node)]);return output;} for(const [key,value] of Object.entries(node)){if(!key.startsWith("$"))collectCssTokens(value,output);} return output; }
export function renderTokensCss(tokens){const declarations=collectCssTokens(tokens).sort(([a],[b])=>a.localeCompare(b)).map(([name,value])=>`  ${name}: ${value};`).join("\n");return `/* Generated from design/tokens.json. Do not edit manually. */\n:root {\n  color-scheme: dark;\n${declarations}\n}\n`;}
function requireSelector(source,selector,id){let present=source.includes(selector);if(selector.startsWith("#")&&/^[#][A-Za-z0-9_-]+$/.test(selector))present=source.includes(`id="${selector.slice(1)}"`);if(!present)throw new Error(`design-system component ${id} references missing selector: ${selector}`);}
export async function validateDesignSystem(){const tokens=JSON.parse(await read("design/tokens.json"));const components=JSON.parse(await read("design/components.json"));const viewports=JSON.parse(await read("design/viewports.json"));const committedCss=await read("public/tokens.css");const expectedCss=renderTokensCss(tokens);if(committedCss!==expectedCss)throw new Error("design tokens drift: public/tokens.css is not generated from design/tokens.json");const css=`${await read("public/styles.css")}\n${await read("public/console.css")}`;const html=`${await read("public/index.html")}\n${await read("public/console.html")}`;const source=`${css}\n${html}`;const ids=new Set();for(const component of components.components??[]){if(!component.id||ids.has(component.id))throw new Error(`duplicate/invalid design component id: ${component.id}`);ids.add(component.id);if(!Array.isArray(component.states)||component.states.length===0)throw new Error(`design-system component ${component.id} has no state contract`);for(const selector of component.selectors??[])requireSelector(source,selector,component.id);}const breakpoints=viewports.breakpoints??{};for(const value of Object.values(breakpoints)){if(!Number.isInteger(value)||value<320)throw new Error(`invalid design-system breakpoint: ${value}`);if(!css.includes(`max-width: ${value}px`))throw new Error(`viewport contract missing CSS breakpoint: ${value}px`);}const preferredTarget=viewports.interaction?.preferredTargetPx;if(preferredTarget!==44)throw new Error(`preferred target contract drifted from 44px: ${preferredTarget}`);if(!committedCss.includes(`--target-min: ${preferredTarget}px;`))throw new Error("target-size token is not represented in generated CSS");if(!css.includes("outline: 2px solid var(--accent)"))throw new Error("focus appearance no longer has the 2px design-system perimeter");return {tokenCount:collectCssTokens(tokens).length,componentCount:ids.size};}
if(process.argv[1]===fileURLToPath(import.meta.url)){const result=await validateDesignSystem();console.log(`design system validated: ${result.tokenCount} CSS tokens, ${result.componentCount} component contracts`);}
