#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

: "${GH_REPO:?GH_REPO must be owner/repository}"
: "${KORPUS_DOMAIN:?KORPUS_DOMAIN is required}"
: "${KORPUS_OIDC_ISSUER:?KORPUS_OIDC_ISSUER is required}"
: "${KORPUS_OIDC_JWKS_URL:?KORPUS_OIDC_JWKS_URL is required}"
: "${KORPUS_OIDC_AUTHORIZATION_ENDPOINT:?KORPUS_OIDC_AUTHORIZATION_ENDPOINT is required}"
: "${KORPUS_OIDC_TOKEN_ENDPOINT:?KORPUS_OIDC_TOKEN_ENDPOINT is required}"
: "${KORPUS_OIDC_CLIENT_ID:?KORPUS_OIDC_CLIENT_ID is required}"
: "${KORPUS_OIDC_AUDIENCE:?KORPUS_OIDC_AUDIENCE is required}"
: "${KORPUS_CLAMAV_SOURCE_IMAGE:?KORPUS_CLAMAV_SOURCE_IMAGE is required}"
: "${KORPUS_MONITORING_CHANNEL_IDS_JSON:?KORPUS_MONITORING_CHANNEL_IDS_JSON is required}"
: "${KORPUS_DATABASE_DISK_AUTOSIZE_LIMIT_GB:?KORPUS_DATABASE_DISK_AUTOSIZE_LIMIT_GB is required}"
: "${KORPUS_OIDC_CLIENT_SECRET:?KORPUS_OIDC_CLIENT_SECRET is required}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
command -v gh >/dev/null 2>&1 || { echo "gh is required" >&2; exit 2; }
gh auth status >/dev/null 2>&1 || { echo "gh is not authenticated" >&2; exit 2; }

# Bootstrap must have established these trust-root variables first.
GCP_PROJECT_ID="$(gh variable get GCP_PROJECT_ID --repo "$GH_REPO")"
TF_STATE_BUCKET="$(gh variable get GCP_TERRAFORM_STATE_BUCKET --repo "$GH_REPO")"
WIF_PROVIDER="$(gh variable get GCP_RUNTIME_WIF_PROVIDER --repo "$GH_REPO")"
DEPLOYER_SA="$(gh variable get GCP_RUNTIME_DEPLOYER_SERVICE_ACCOUNT --repo "$GH_REPO")"
DOMAIN="$KORPUS_DOMAIN"
OIDC_ISSUER="$KORPUS_OIDC_ISSUER"
OIDC_JWKS_URL="$KORPUS_OIDC_JWKS_URL"
OIDC_AUTH_ENDPOINT="$KORPUS_OIDC_AUTHORIZATION_ENDPOINT"
OIDC_TOKEN_ENDPOINT="$KORPUS_OIDC_TOKEN_ENDPOINT"
OIDC_END_SESSION_ENDPOINT="${KORPUS_OIDC_END_SESSION_ENDPOINT:-}"
OIDC_CLIENT_ID="$KORPUS_OIDC_CLIENT_ID"
OIDC_AUDIENCE="$KORPUS_OIDC_AUDIENCE"
CLAMAV_SOURCE_IMAGE="$KORPUS_CLAMAV_SOURCE_IMAGE"
MONITORING_CHANNELS="$KORPUS_MONITORING_CHANNEL_IDS_JSON"
DATABASE_DISK_AUTOSIZE_LIMIT_GB="$KORPUS_DATABASE_DISK_AUTOSIZE_LIMIT_GB"
OTLP_ENDPOINT="${KORPUS_OTLP_ENDPOINT:-}"
export GCP_PROJECT_ID TF_STATE_BUCKET DOMAIN WIF_PROVIDER DEPLOYER_SA OIDC_ISSUER OIDC_JWKS_URL OIDC_AUTH_ENDPOINT OIDC_TOKEN_ENDPOINT OIDC_END_SESSION_ENDPOINT OIDC_CLIENT_ID OIDC_AUDIENCE CLAMAV_SOURCE_IMAGE MONITORING_CHANNELS DATABASE_DISK_AUTOSIZE_LIMIT_GB OTLP_ENDPOINT
python3 "$ROOT/scripts/gcp/production_inputs.py" --probe-oidc --output "$ROOT/reports/production/external-inputs.json" >/dev/null

set_var() { printf '%s' "$2" | gh variable set "$1" --repo "$GH_REPO" >/dev/null; }
set_var KORPUS_DOMAIN "$KORPUS_DOMAIN"
set_var KORPUS_OIDC_ISSUER "$KORPUS_OIDC_ISSUER"
set_var KORPUS_OIDC_JWKS_URL "$KORPUS_OIDC_JWKS_URL"
set_var KORPUS_OIDC_AUTHORIZATION_ENDPOINT "$KORPUS_OIDC_AUTHORIZATION_ENDPOINT"
set_var KORPUS_OIDC_TOKEN_ENDPOINT "$KORPUS_OIDC_TOKEN_ENDPOINT"
set_var KORPUS_OIDC_END_SESSION_ENDPOINT "${KORPUS_OIDC_END_SESSION_ENDPOINT:-}"
set_var KORPUS_OIDC_CLIENT_ID "$KORPUS_OIDC_CLIENT_ID"
set_var KORPUS_OIDC_AUDIENCE "$KORPUS_OIDC_AUDIENCE"
set_var KORPUS_CLAMAV_SOURCE_IMAGE "$KORPUS_CLAMAV_SOURCE_IMAGE"
set_var KORPUS_MONITORING_CHANNEL_IDS_JSON "$KORPUS_MONITORING_CHANNEL_IDS_JSON"
set_var KORPUS_DATABASE_DISK_AUTOSIZE_LIMIT_GB "$KORPUS_DATABASE_DISK_AUTOSIZE_LIMIT_GB"
set_var KORPUS_OTLP_ENDPOINT "${KORPUS_OTLP_ENDPOINT:-}"

# Environment scope prevents routine runtime jobs from receiving the OIDC client secret.
printf '%s' "$KORPUS_OIDC_CLIENT_SECRET" | gh secret set KORPUS_OIDC_CLIENT_SECRET --repo "$GH_REPO" --env production-foundation >/dev/null
unset KORPUS_OIDC_CLIENT_SECRET
printf 'PASS: external production inputs validated, OIDC discovery matched, GitHub variables configured.\n'
printf 'Production remains disabled until foundation/live gates pass.\n'
