apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: korpus
resources:
  - ../../base
patches:
  - target: {kind: Deployment, name: korpus-api}
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target: {kind: Deployment, name: korpus-worker}
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target: {kind: Deployment, name: korpus-web}
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
