data "terraform_remote_state" "foundation" {
  backend = "gcs"
  config = {
    bucket = var.state_bucket
    prefix = var.foundation_state_prefix
  }
}

locals {
  foundation      = data.terraform_remote_state.foundation.outputs
  service_accounts = local.foundation.service_accounts
  buckets          = local.foundation.buckets
  secrets          = local.foundation.secrets
  cloud_sql_name   = local.foundation.cloud_sql_connection_name
  runtime_network   = local.foundation.runtime_network
  origin           = "https://${var.domain}"
  api_redirect_uri = "https://${var.domain}/api/v1/auth/callback"
  governance_root = "/etc/korpus/governance/releases/${var.governance_release_id}"

  database_url_template = "postgresql+psycopg://korpus_app:{password}@/korpus?host=/cloudsql/${local.cloud_sql_name}"
  admin_database_url_template = "postgresql+psycopg://postgres:{password}@/korpus?host=/cloudsql/${local.cloud_sql_name}"

  api_env = {
    KORPUS_ENVIRONMENT                       = "production"
    KORPUS_RUNTIME_ROLE                      = "api"
    KORPUS_DATABASE_TRANSPORT                = "cloud_sql_socket"
    KORPUS_DATABASE_URL_TEMPLATE             = local.database_url_template
    KORPUS_DATABASE_PASSWORD_FILE            = "/secrets/db-app/password"
    KORPUS_SCHEMA_MODE                       = "migrations"
    KORPUS_OBJECT_STORE_MODE                 = "gcs"
    KORPUS_GCS_BUCKET                        = local.buckets.objects
    KORPUS_GCS_PREFIX                        = "objects"
    KORPUS_GCS_QUARANTINE_BUCKET             = local.buckets.quarantine
    KORPUS_GCS_QUARANTINE_PREFIX             = "quarantine"
    KORPUS_GCS_RETENTION_SECONDS             = tostring(local.foundation.object_retention_seconds)
    KORPUS_AUDIT_ANCHOR_MODE                 = "gcs"
    KORPUS_GCS_AUDIT_BUCKET                  = local.buckets.audit
    KORPUS_GCS_AUDIT_PREFIX                  = "audit/anchors"
    KORPUS_AUDIT_HMAC_KEY_FILE               = "/secrets/audit-hmac/key"
    KORPUS_AUTH_MODE                         = "oidc"
    KORPUS_JWT_ISSUER                        = var.oidc_issuer
    KORPUS_JWT_AUDIENCE                      = var.oidc_audience
    KORPUS_OIDC_JWKS_URL                     = var.oidc_jwks_url
    KORPUS_OIDC_AUTHORIZATION_ENDPOINT       = var.oidc_authorization_endpoint
    KORPUS_OIDC_TOKEN_ENDPOINT               = var.oidc_token_endpoint
    KORPUS_OIDC_END_SESSION_ENDPOINT         = var.oidc_end_session_endpoint
    KORPUS_OIDC_CLIENT_ID                    = var.oidc_client_id
    KORPUS_OIDC_CLIENT_SECRET_FILE           = "/secrets/oidc-client/secret"
    KORPUS_OIDC_REDIRECT_URI                 = local.api_redirect_uri
    KORPUS_BROWSER_AUTH_ENABLED              = "true"
    KORPUS_BROWSER_SESSION_KEY_FILE          = "/secrets/browser-session/key"
    KORPUS_BROWSER_COOKIE_SECURE             = "true"
    KORPUS_ENTITLEMENT_PROFILE_PATH          = "${local.governance_root}/entitlements.json"
    KORPUS_ENTITLEMENT_PROFILE_SHA256        = var.entitlement_profile_sha256
    KORPUS_SOURCE_TRUST_PROFILE_PATH         = "${local.governance_root}/source-trust.json"
    KORPUS_SOURCE_TRUST_PROFILE_SHA256       = var.source_trust_profile_sha256
    KORPUS_REQUIRE_SOURCE_SIGNATURES         = "true"
    KORPUS_REVIEWER_REGISTRY_PATH            = "${local.governance_root}/reviewers.json"
    KORPUS_REVIEWER_REGISTRY_SHA256          = var.reviewer_registry_sha256
    KORPUS_CORPUS_GOVERNANCE_PROFILE_PATH    = "${local.governance_root}/corpus-governance.json"
    KORPUS_CORPUS_GOVERNANCE_PROFILE_SHA256  = var.corpus_governance_profile_sha256
    KORPUS_ANSWER_POLICY_MODE                = "calibrated"
    KORPUS_CALIBRATION_PROFILE_PATH          = "${local.governance_root}/calibration.json"
    KORPUS_CALIBRATION_PROFILE_SHA256        = var.calibration_profile_sha256
    KORPUS_CALIBRATION_DATASET_PATH          = "${local.governance_root}/calibration-dataset.jsonl"
    KORPUS_CALIBRATION_SYSTEM_MANIFEST_PATH  = "${local.governance_root}/system-manifest.json"
    KORPUS_CALIBRATION_EVALUATION_PROTOCOL_PATH = "${local.governance_root}/evaluation-protocol.md"
    KORPUS_ANSWER_COMPOSER_ENABLED           = "false"
    KORPUS_QUERY_PLANNER_ENABLED             = "false"
    KORPUS_MODEL_EGRESS_POSTURE              = "model_disabled"
    KORPUS_SEMANTIC_RETRIEVAL_ENABLED        = "false"
    KORPUS_SEMANTIC_WEIGHT                   = "0"
    KORPUS_REVIEW_SEPARATION_REQUIRED        = "true"
    KORPUS_INGESTION_MODE                    = "durable_async"
    KORPUS_MALWARE_SCAN_MODE                 = "disabled"
    KORPUS_PARSER_SANDBOX_ENABLED            = "false"
    KORPUS_METRICS_ENABLED                   = "true"
    KORPUS_METRICS_TOKEN_FILE                = "/secrets/metrics/token"
    KORPUS_OTLP_ENDPOINT                     = var.otlp_endpoint
    KORPUS_CORS_ORIGINS                      = local.origin
    KORPUS_TRUSTED_HOSTS                     = var.domain
    KORPUS_SERVICE_NAME                      = "korpus-api"
  }

  worker_env = {
    KORPUS_ENVIRONMENT                      = "production"
    KORPUS_RUNTIME_ROLE                     = "worker"
    KORPUS_DATABASE_TRANSPORT               = "cloud_sql_socket"
    KORPUS_DATABASE_URL_TEMPLATE            = local.database_url_template
    KORPUS_DATABASE_PASSWORD_FILE           = "/secrets/db-app/password"
    KORPUS_SCHEMA_MODE                      = "migrations"
    KORPUS_OBJECT_STORE_MODE                = "gcs"
    KORPUS_GCS_BUCKET                       = local.buckets.objects
    KORPUS_GCS_PREFIX                       = "objects"
    KORPUS_GCS_QUARANTINE_BUCKET            = local.buckets.quarantine
    KORPUS_GCS_QUARANTINE_PREFIX            = "quarantine"
    KORPUS_GCS_RETENTION_SECONDS            = tostring(local.foundation.object_retention_seconds)
    KORPUS_AUDIT_ANCHOR_MODE                = "gcs"
    KORPUS_GCS_AUDIT_BUCKET                 = local.buckets.audit
    KORPUS_GCS_AUDIT_PREFIX                 = "audit/anchors"
    KORPUS_AUDIT_HMAC_KEY_FILE              = "/secrets/audit-hmac/key"
    KORPUS_AUTH_MODE                        = "disabled"
    KORPUS_SOURCE_TRUST_PROFILE_PATH        = "${local.governance_root}/source-trust.json"
    KORPUS_SOURCE_TRUST_PROFILE_SHA256      = var.source_trust_profile_sha256
    KORPUS_REQUIRE_SOURCE_SIGNATURES        = "true"
    KORPUS_REVIEWER_REGISTRY_PATH           = "${local.governance_root}/reviewers.json"
    KORPUS_REVIEWER_REGISTRY_SHA256         = var.reviewer_registry_sha256
    KORPUS_CORPUS_GOVERNANCE_PROFILE_PATH   = "${local.governance_root}/corpus-governance.json"
    KORPUS_CORPUS_GOVERNANCE_PROFILE_SHA256 = var.corpus_governance_profile_sha256
    KORPUS_ANSWER_POLICY_MODE               = "development"
    KORPUS_REVIEW_SEPARATION_REQUIRED       = "true"
    KORPUS_INGESTION_MODE                   = "durable_async"
    KORPUS_MALWARE_SCAN_MODE                = "clamd"
    KORPUS_CLAMD_HOST                       = "127.0.0.1"
    KORPUS_CLAMD_PORT                       = "3310"
    KORPUS_PARSER_SANDBOX_ENABLED           = "true"
    KORPUS_METRICS_ENABLED                  = "false"
    KORPUS_OTLP_ENDPOINT                    = var.otlp_endpoint
    KORPUS_SERVICE_NAME                     = "korpus-worker"
  }
}
