#!/usr/bin/env python3
"""Emit the browser's copy of the request constraints from the OpenAPI contract.

WEB-001 needs forms that validate before they submit — otherwise every typo costs a
round trip and comes back as a 422 that names a JSON path rather than a field. The
hazard in writing that validation by hand is that it becomes a second, unversioned copy
of the domain rules, and the copy drifts: a `min_length` raised in `models.py` leaves a
form that happily submits what the server will refuse, or — worse, because it is
invisible — a form that refuses what the server would have accepted.

So the constraints are generated from `contracts/openapi.json`, which is itself
generated from the running app and drift-gated by `scripts/openapi_contract.py`. There
is exactly one place a field length is written down.

What this deliberately does not generate is the *semantic* rules — that
`access_tier` must reach `classification.minimum_tier`, that `effective_until` cannot
precede `effective_from`. Those are model validators, they do not appear in JSON Schema,
and hand-writing them in the client would recreate the drift this file exists to
prevent. The client checks what the schema states; the server remains the authority, and
its refusal is rendered verbatim.

`--check` fails when the emitted file is stale, so the pipeline catches a schema change
that nobody carried into the browser.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps/api/src"))

from korpus.application.policy import ROLE_PERMISSIONS  # noqa: E402  (path set above)

CONTRACT = ROOT / "contracts/openapi.json"
TARGET = ROOT / "apps/web/public/contract.js"

#: The request bodies the consoles build. Response models are read, not constructed, so
#: a stale constraint on them cannot produce a rejected submission.
MODELS = ("DocumentCreate", "VersionCreate", "ReviewTransition", "RescissionRequest")
ENUMS = ("AccessTier", "Classification", "AuthorityClass", "ReviewState")


def _unwrap(schema: dict[str, Any]) -> dict[str, Any]:
    """Collapse `anyOf: [X, null]` to X and resolve a `$ref` to its enum name.

    Optional fields arrive as a two-branch union. Reading `maxLength` off the union
    itself finds nothing, which would silently emit a field with no constraints — the
    permissive direction, and the one that produces a 422 the user cannot predict.
    """
    if "$ref" in schema:
        return {"enum_ref": schema["$ref"].rsplit("/", 1)[-1]}
    branches = schema.get("anyOf")
    if isinstance(branches, list):
        concrete = [item for item in branches if item.get("type") != "null"]
        nullable = len(concrete) != len(branches)
        if len(concrete) == 1:
            resolved = _unwrap(concrete[0])
            resolved["nullable"] = nullable
            return resolved
    return dict(schema)


def _field(name: str, schema: dict[str, Any], required: bool) -> dict[str, Any]:
    resolved = _unwrap(schema)
    field: dict[str, Any] = {"name": name, "required": required}
    for key in ("type", "format", "pattern", "minLength", "maxLength", "default"):
        if key in resolved:
            field[key] = resolved[key]
    if "enum_ref" in resolved:
        field["enum"] = resolved["enum_ref"]
    if resolved.get("nullable"):
        field["nullable"] = True
    return field


def build(contract: dict[str, Any]) -> dict[str, Any]:
    schemas = contract["components"]["schemas"]
    models = {}
    for model in MODELS:
        definition = schemas[model]
        required = set(definition.get("required", ()))
        models[model] = [
            _field(name, schema, name in required)
            for name, schema in sorted(definition.get("properties", {}).items())
        ]
    enums = {name: list(schemas[name]["enum"]) for name in ENUMS}
    # The role table decides which console a reader is *shown*. It was a hand-copied
    # mirror of policy.py for one commit, which is one commit longer than a duplicated
    # authorization table should exist: a permission added to `curator` there and not
    # here leaves a curator staring at a page that hides the console they now hold.
    roles = {role: sorted(permissions) for role, permissions in sorted(ROLE_PERMISSIONS.items())}
    return {"models": models, "enums": enums, "roles": roles}


def render(payload: dict[str, Any]) -> str:
    body = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "// Generated by scripts/generate_web_contract.py from contracts/openapi.json.\n"
        "// Do not edit: a hand-edit here is a second copy of the domain rules, and the\n"
        "// copy is the one that drifts. Regenerate with `make web-contract`.\n"
        f"export const CONTRACT = {body};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not CONTRACT.is_file():
        print(json.dumps({"valid": False, "reason": "contracts/openapi.json missing"}))
        return 2
    rendered = render(build(json.loads(CONTRACT.read_text(encoding="utf-8"))))

    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != rendered:
            print(
                json.dumps(
                    {
                        "valid": False,
                        "reason": (
                            "the browser's copy of the request constraints is stale; the "
                            "forms would validate against rules the API no longer has"
                        ),
                        "regenerate_with": "make web-contract",
                    },
                    ensure_ascii=False,
                    indent=2,
                )
            )
            return 1
        print(json.dumps({"valid": True, "models": len(MODELS), "enums": len(ENUMS)}))
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(json.dumps({"valid": True, "written": str(TARGET.relative_to(ROOT))}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
