#!/usr/bin/env python3
"""Generate the consumer transport contract from canonical OpenAPI + release identity."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps/api/src"))

from korpus.release import RELEASE_TAG  # noqa: E402

OPENAPI = ROOT / "contracts/openapi.json"
TARGET = ROOT / "apps/web/public/transport_contract.js"
HTTP_METHODS = frozenset({"get", "post", "put", "patch", "delete", "head", "options"})
# Browser-session endpoints intentionally excluded from the public OpenAPI still cross
# the same transport boundary. Keeping the exception list here makes it reviewable and
# generated rather than a permissive bypass in api.js.
HIDDEN_BROWSER_ROUTES = {"/v1/auth/logout": ["POST"]}


def build(contract: dict[str, Any]) -> dict[str, Any]:
    paths: dict[str, list[str]] = {}
    for path, operations in sorted(contract.get("paths", {}).items()):
        methods = sorted(method.upper() for method in operations if method in HTTP_METHODS)
        if methods:
            paths[path] = methods
    return {
        "release": RELEASE_TAG,
        "api_version": "v1",
        "paths": paths,
        "hidden_browser_routes": HIDDEN_BROWSER_ROUTES,
    }


def render(payload: dict[str, Any]) -> str:
    body = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return (
        "// Generated by scripts/generate_transport_contract.py from canonical OpenAPI.\n"
        "// Do not edit; stale browser endpoints must fail before network execution.\n"
        f"export const TRANSPORT_CONTRACT = Object.freeze({body});\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if not OPENAPI.is_file():
        raise SystemExit("contracts/openapi.json missing")
    rendered = render(build(json.loads(OPENAPI.read_text(encoding="utf-8"))))
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != rendered:
            print(json.dumps({"valid": False, "reason": "transport contract stale"}))
            return 1
        payload = build(json.loads(OPENAPI.read_text(encoding="utf-8")))
        print(json.dumps({"valid": True, "release": payload["release"], "paths": len(payload["paths"])}))
        return 0
    TARGET.write_text(rendered, encoding="utf-8")
    print(json.dumps({"valid": True, "written": str(TARGET.relative_to(ROOT))}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
